services:
  backend:
    networks:
      - openbuilder-ui_default
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/downloads:/app/downloads
      - ./frontend:/frontend
      - ~/workspace/openbuilder-workspace:/Users/kaka/workspace/openbuilder-workspace
      - ~/workspace/code/openbuilder:/root/workspace/code/openbuilder
      - ./backend/builds.json:/app/builds.json
      # Docker socket to run dockcross containers from within backend
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Shanghai
      - WORKSPACE_DIR=/Users/kaka/workspace/openbuilder-workspace
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENBUILDER_S3_ENDPOINT=http://host.docker.internal:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  openbuilder-ui_default:
    driver: bridge
